Update colleciton model and store
netwerk-digitaal-erfgoed/solid-crs pull request #227
Opened 2021-05-21 12:34 UTC by lem-onade

2021-05-27 09:18 UTC, BelgianNoise approved these changes
I didn't look at every line of code but it seems to work fine in the UI and the solid store looks great.

2021-05-27 11:20 UTC, BelgianNoise submitted a review, later dismissed

2021-05-28 05:20 UTC, wouteraj requested changes
Looks very good!!! One major remark: it seems that creating objects isn't working yet, even though you made the necessary code changes. Is this supposed to work?

2021-05-28 05:20 UTC, wouteraj commented on packages/solid-crs-manage/lib/features/collection/collection.machine.ts
> +        [CollectionEvents.CANCELLED_EDIT]: CollectionStates.IDLE,
I would thinks these events should only have effect when `IDLE`.

2021-05-28 08:21 UTC, wouteraj approved these changes

2021-05-28 08:45 UTC, BelgianNoise approved these changes

2021-05-28 08:45 UTC, merged