Feat/create nde large card
netwerk-digitaal-erfgoed/solid-crs pull request #243
Opened 2021-05-26 12:52 UTC by BelgianNoise

2021-05-26 13:34 UTC, BelgianNoise commented
Examples can be found on port 3001

2021-05-26 13:58 UTC, wouteraj requested changes
Looks good; added a small remark.

2021-05-26 13:58 UTC, wouteraj commented on packages/solid-crs-components/lib/collections/large-card.component.ts
> +            </div>
Might be best to re-use the `ContentHeaderComponent` instead of making a new component.

2021-05-26 14:58 UTC, lem-onade approved these changes

2021-05-26 14:58 UTC, lem-onade commented on packages/solid-crs-components/lib/collections/large-card.component.ts
> +          : 0;
```suggestion
          gap: 0;
```

2021-05-27 14:54 UTC, lem-onade submitted a review, later dismissed
nice!

2021-05-28 05:00 UTC, wouteraj approved these changes
Looks great!!

2021-05-28 05:00 UTC, merged