feat: add confirmation when deleting collections and objects
netwerk-digitaal-erfgoed/solid-crs pull request #433
Opened 2021-08-20 09:27 UTC by arnevandoorslaer

2021-08-20 12:25 UTC, lem-onade requested changes

2021-08-20 12:25 UTC, lem-onade commented on packages/solid-crs-manage/lib/features/collection/collection-root.component.ts
> +          margin: 40px 5px 0;
```suggestion
          margin: var(--gap-large) var(--gap-tiny) 0;
```

2021-08-20 12:25 UTC, lem-onade commented on packages/solid-crs-manage/lib/features/collection/collection-root.component.ts
> +          color: white;
```suggestion
          color: var(--colors-foreground-inverse);
```

2021-08-20 12:25 UTC, lem-onade commented on packages/solid-crs-manage/lib/features/collection/collection-root.component.ts
> +          height: 45px;
Check if needed

2021-08-20 12:25 UTC, lem-onade commented on packages/solid-crs-manage/lib/features/collection/collection-root.component.ts
> +          padding: 40px;
```suggestion
          padding: var(--gap-large);
```

2021-08-20 12:25 UTC, lem-onade commented on packages/solid-crs-manage/lib/features/collection/collection-root.component.ts
> +          background-color: white;
```suggestion
          background-color: var(--colors-foreground-inverse);
```

2021-08-20 12:25 UTC, lem-onade commented on packages/solid-crs-manage/lib/features/object/object-root.component.ts
> +          margin: 40px 5px 0;
```suggestion
          margin: var(--gap-large) var(--gap-tiny) 0;
```

2021-08-20 12:25 UTC, lem-onade commented on packages/solid-crs-manage/lib/features/object/object-root.component.ts
> +          padding: 40px;
```suggestion
          padding: var(--gap-large);
```

2021-08-20 12:25 UTC, lem-onade commented on packages/solid-crs-manage/lib/features/object/object-root.component.ts
> +          background-color: white;
See other color comments

2021-08-20 12:25 UTC, lem-onade commented on packages/solid-crs-manage/lib/features/object/object-root.component.ts
> +          color: white;
See other color comments

2021-08-20 12:27 UTC, BelgianNoise requested changes
^ the above

2021-08-23 08:42 UTC, lem-onade approved these changes

2021-08-23 08:42 UTC, lem-onade commented on packages/solid-crs-manage/lib/i8n/nl-NL.json
> +    },
These can probably go under the same key, under "common" at the bottom of the file. No need to change it in this PR, perhaps keep in mind when doing https://github.com/netwerk-digitaal-erfgoed/solid-crs/issues/336

2021-08-23 08:43 UTC, lem-onade commented on packages/solid-crs-manage/lib/i8n/nl-NL.json
> +    },
(same key as the object confirm and cancel)

2021-08-23 09:40 UTC, BelgianNoise approved these changes

2021-08-23 09:43 UTC, merged