feat: improved copy url in presentation
netwerk-digitaal-erfgoed/solid-crs pull request #559
Opened 2022-01-19 16:37 UTC by BelgianNoise

2022-01-20 10:52 UTC, lem-onade commented on packages/solid-crs-presentation/lib/public/nl-NL.json
> -        "copied-image-url": "De URL van de afbeelding werd gekopieerd.",
Looks and works fine, OK for me

2022-01-20 10:52 UTC, lem-onade approved these changes

2022-01-20 14:19 UTC, johannadm requested changes
Looks good and works well, but after discussing the scope and UI, we noticed that the 'URL' should be a 'URI'. So this should be changed.

2022-01-24 16:13 UTC, johannadm approved these changes

2022-01-24 16:27 UTC, merged